# Generated by Django 4.1.3 on 2022-12-05 11:42

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('coupon', models.AutoField(primary_key=True, serialize=False)),
                ('coupon_code', models.CharField(max_length=35, unique=True)),
                ('valid_num_of_use', models.IntegerField(default=1)),
                ('percent', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order', models.AutoField(primary_key=True, serialize=False)),
                ('payment_method', models.CharField(choices=[('online', 'online'), ('on_delivery', 'on delivery')], default='online', max_length=20)),
                ('payment_stat', models.CharField(choices=[('done_online', 'done online'), ('done_on_delivery', 'done on delivery'), ('not_payed', 'not payed')], default='not_payed', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=50)),
                ('description', models.TextField(null=True)),
                ('order_stat', models.CharField(choices=[('delivered', 'delivered'), ('in_line_for_delivery', 'in line for delivery')], max_length=30, null=True)),
                ('address', models.TextField()),
                ('created_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('used_coupon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.coupons')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProduct_Cart',
            fields=[
                ('UserProduct_Cart', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(default=1)),
                ('stat', models.CharField(choices=[('in_cart', 'in cart'), ('in_order', 'in order')], default='in_cart', max_length=20)),
                ('created_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.orders')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccountDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
